-- =====================================================================================
-- V1: Modo CRON de la integración ML (EntrenamientoAI)
--
-- Crea las tablas que el Render Cron Job (Python) escribe en Neon y que el backend
-- lee en modo CRON, y amplía los CHECK de los enums de pipelines/kpi_resultados para
-- aceptar los valores ML.
--
-- Apta para PostgreSQL (Neon). Es idempotente y segura de re-ejecutar: usa
-- "IF NOT EXISTS" y guarda contra tablas inexistentes con to_regclass.
--
-- Cómo aplicarla:
--   * Manual (recomendado en este proyecto, que usa ddl-auto=update):
--       psql "$DB_URL" -f src/main/resources/db/migration/V1__ml_cron_tables.sql
--   * O activando Flyway (ver README): añadir la dependencia flyway-core +
--     flyway-database-postgresql y FLYWAY_ENABLED=true.
-- =====================================================================================

-- ── Tabla ml_metricas ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ml_metricas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts                TIMESTAMP        NOT NULL,
    accuracy          DOUBLE PRECISION,
    recall            DOUBLE PRECISION,
    precision         DOUBLE PRECISION,
    f1                DOUBLE PRECISION,
    roc_auc           DOUBLE PRECISION,
    gini              DOUBLE PRECISION,
    matriz_confusion  TEXT,
    modelo            VARCHAR(120),
    n_samples         INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ml_metricas_ts ON ml_metricas (ts DESC);

-- ── Tabla ml_predicciones ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ml_predicciones (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts            TIMESTAMP        NOT NULL,
    entidad       VARCHAR(60),
    entidad_id    BIGINT,
    score         DOUBLE PRECISION,
    probabilidad  DOUBLE PRECISION,
    prediccion    VARCHAR(120)
);

CREATE INDEX IF NOT EXISTS idx_ml_predicciones_ts ON ml_predicciones (ts DESC);

-- ── Permitir 'ML' en pipelines.tipo ───────────────────────────────────────────────────
-- Hibernate genera un CHECK con nombre autogenerado; se eliminan los CHECK que referencien
-- la columna "tipo" y se recrea uno inclusivo. Solo se ejecuta si la tabla ya existe.
DO $$
DECLARE c record;
BEGIN
    IF to_regclass('public.pipelines') IS NOT NULL THEN
        FOR c IN
            SELECT con.conname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            WHERE rel.relname = 'pipelines'
              AND con.contype = 'c'
              AND pg_get_constraintdef(con.oid) ILIKE '%tipo%'
        LOOP
            EXECUTE format('ALTER TABLE pipelines DROP CONSTRAINT %I', c.conname);
        END LOOP;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pipelines_tipo_check') THEN
            ALTER TABLE pipelines ADD CONSTRAINT pipelines_tipo_check
                CHECK (tipo IN ('SOLICITUD_COMPRA', 'COTIZACION', 'ORDEN_COMPRA', 'KPI', 'ML'));
        END IF;
    END IF;
END $$;

-- ── Permitir valores ML_* en kpi_resultados.tipo ──────────────────────────────────────
DO $$
DECLARE c record;
BEGIN
    IF to_regclass('public.kpi_resultados') IS NOT NULL THEN
        FOR c IN
            SELECT con.conname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            WHERE rel.relname = 'kpi_resultados'
              AND con.contype = 'c'
              AND pg_get_constraintdef(con.oid) ILIKE '%tipo%'
        LOOP
            EXECUTE format('ALTER TABLE kpi_resultados DROP CONSTRAINT %I', c.conname);
        END LOOP;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'kpi_resultados_tipo_check') THEN
            ALTER TABLE kpi_resultados ADD CONSTRAINT kpi_resultados_tipo_check
                CHECK (tipo IN ('AHORRO', 'TIEMPO_CICLO', 'COTIZACIONES_RECIBIDAS', 'ORDENES_EMITIDAS',
                                'ML_ACCURACY', 'ML_PRECISION', 'ML_RECALL', 'ML_F1', 'ML_ROC_AUC', 'ML_GINI'));
        END IF;
    END IF;
END $$;
